### ISSUE TITLE
Make UMD code think that it is running under Node.js by undefining define()

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#111]
Even though the bundler's generated code gets run in an AMD context, developers are supposed to target Node.js module management (CommonJS) when writing their code (for `liferay-npm-bundler` version series `2.x.x`, version series `1.x.x` didn't make such assumption for user's Javascript code but only for `node_modules` code).

For such assumption to work, the `define` symbol must not be available for the module definitions because otherwise it may branch execution and try to make the AMD definition itself, leading to tiemout, empty definition, or incorrect naming problems with the loader.

**Comment by wsyski** [comment]
I have tried to test: "Liferay bundler/loader issue with @angular/common/http" with angular-npm-portlet 
1. Updated "liferay-npm-bundler": "v2.0.0-rc.2"
2. remove the "module": "amd" option of tsconfig.json
Now I get " angularNpmPortlet100.default is not a function"
Do I need to change anything else?

**Comment by izaera** [comment]
@wsyski you need to remove the call to babel in package.json:

https://github.com/liferay/liferay-blade-samples/blob/master/gradle/apps/npm/angular-npm-portlet/package.json#L59

Also, you need to delete or empty the .npmbundlerrc file as the angular presets is not used any more:

https://github.com/liferay/liferay-blade-samples/blob/master/gradle/apps/npm/angular-npm-portlet/.npmbundlerrc#L2

And I think that's enough...
