### ISSUE TITLE
The "May xxx anonymously report usage statistics to improve the tool over time?" message may be a problem in big builds

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#118]
Say you have a big project with 100 portlets shared across your whole company and you use liferay-npm-bundler in each one of them.

The first time you download the big project and build it you will get the same question a hundred times.

Maybe we should provide some way to disable/enable usage statistics for the whole tool system-wide, not just for each project.

**Comment by izaera** [comment]
I'm finally asking for the whole tool (not per project). That way, if the notice appears it will only appear once.

**Comment by jbalsas** [comment]
I like @yuchi suggestion very much, so on top of asking, I'd implement the `--no-tracking` flag that could override anything on a per-project basis.

**Comment by izaera** [comment]
no need to do that, just use the `CI=1` option

**Comment by izaera** [comment]
as @yuchi said

**Comment by izaera** [comment]
After discussing it a bit in private, we are implementing:

1. Never ask on a per-project basis, but for the whole system
2. Running `CI=1 liferay-npm-bundler` disables reporting
3. Running `liferay-npm-bundler --no-tracking` disables reporting
4. Having a file called `.liferay-npm-bundler-no-insight` in the project's folder or any of its ancestors disables reporting (corollary: creating a file `.liferay-npm-bundler-no-tracking` in your `/` folder equates to answering `No` to the `May liferay-npm-bundler anonymously report usage statistics to improve the tool over time?` question).

**Comment by izaera** [comment]
This one is fixed by commit c54f2eeb1f4128919bacc36d7437d32200fd7297
