### ISSUE TITLE
Let liferay-npm-bridge-generator be configured with a .npmbridgerc file

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#124]
The idea is to be able to give one or more execution descriptions in a `.npmbridgerc` instead of passing them through the command line.

This is to avoid errors with npm scripts when they are run in multiple platforms, because some of the `liferay-npm-bridge-generator` are regular expressions and they don't play well with the different sells (cmd.exe vs bash/whatever) when escaped as arguments.

It is important to be able to specify more than one run in the file, as it is unique to the project, but the generator may need to be run more than once per project.

**Comment by izaera** [comment]
An example of an `.npmbridgesrc` file:

```json
{
	liferay: {
		"input": "classes/META-INF/resources",
		"output": "classes/META-INF/resources/bridge/frontend-js-web",
		"file-globs": "liferay/**/*.js",
		"src-mod-name-mapper": {
			"from": "(.*)\\.js$",
			"to": "frontend-js-web/$1"
		},
		"dest-file-mapper": {
			"from": "(.*)\\$(.*)@.*/lib/(.*)",
			"to": "$2/src/$3"
		}
		"dest-mod-name-mapper": {
			"from": "(.*)\\.js$",
			"to": "bridge/frontend-js-web/$1"
		}
	}
}
```

**Comment by jbalsas** [comment]
Is it `.npmbridgesrc` or `.npmbridgerc`?

**Comment by izaera** [comment]
The first one.

**Comment by izaera** [comment]
I feel `.npmbridgegeneratorrc` is a bit horrible and difficult to read/write. But maybe we can pass the file name as an argument in the CLI and that way the user decides how to call it... 🤔 

Or we can use `.npmbridgegeneratorrc` 😬

**Comment by izaera** [comment]
I misunderstood your comment https://github.com/liferay/liferay-npm-build-tools/issues/124#issuecomment-393057521 @jbalsas. It's true that the tools is named in singular, so I'll call the file `.npmbridgerc` 👍
