### ISSUE TITLE
Missing plugin READMEs

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-build-tools#13]
By convention, all babel plugins contain a README specifying:

# babel-plugin-foo

> Foo does Bar

## Example

```js
// Some code here
```

## Installation

```sh
npm install --save-dev babel-plugin-foo
```

### Via `.babelrc` (Recommended)

**.babelrc**

```json
{
  "plugins": ["foo"]
}
```

### Via CLI

```sh
babel --plugins foo script.js
```

### Via Node API

```javascript
require("babel-core").transform("code", {
  plugins: ["foo"]
});
```

## References

* Links to reference if any
* [babel-plugin-transform-exponentiation-operator/README.md](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-exponentiation-operator/README.md)
* [babel-plugin-transform-class-properties/README.md](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-class-properties/README.md)

We are currently missing those for our own plugins and shouldn't

**Comment by izaera** [comment]
I'm closing this because all subprojects have been documented.

**Comment by jbalsas** [comment]
👏

**Comment by izaera** [comment]
https://github.com/liferay/liferay-npm-build-tools/commit/b70c775b7adfaee028d93dd3b24722a19a0cbebf#diff-0b1b546d30928b71c8123b3466a1d441
