### ISSUE TITLE
liferay-npm-bundler fails with angular 6

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-npm-build-tools#141]
Tried to upgrade the standard angular-npm-portlet from blade examples to angular 6. Got the following error:
<pre>
> angular-npm-portlet@1.0.0 build /opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet
> tsc && liferay-npm-bundler

Bundling 18 dependencies...
{ Error: ENOENT: no such file or directory, open '/opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/build/resources/main/META-INF/resources/node_modules/@angular%2Fplatform-browser-dynamic@6.0.4/esm2015/src/data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxhdGZvcm1fY29yZV9keW5hbWljLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vLi4vLi4vLi4vLi4vcGFja2FnZXMvcGxhdGZvcm0tYnJvd3Nlci1keW5hbWljL3NyYy9wbGF0Zm9ybV9jb3JlX2R5bmFtaWMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7QUFRQSxPQUFPLEVBQUMsZ0JBQWdCLEVBQUUsZUFBZSxFQUErQixxQkFBcUIsRUFBRSxZQUFZLEVBQUMsTUFBTSxlQUFlLENBQUM7QUFDbEksT0FBTyxFQUFDLGtCQUFrQixFQUFDLE1BQU0sb0JBQW9CLENBQUM7Ozs7OztBQU90RCxNQUFNLENBQUMsdUJBQU0sbUJBQW1CLEdBQUcscUJBQXFCLENBQUMsWUFBWSxFQUFFLGFBQWEsRUFBRTtJQUNwRixFQUFDLE9BQU8sRUFBRSxnQkFBZ0IsRUFBRSxRQUFRLEVBQUUsRUFBRSxFQUFFLEtBQUssRUFBRSxJQUFJLEVBQUM7SUFDdEQsRUFBQyxPQUFPLEVBQUUsZUFBZSxFQUFFLFFBQVEsRUFBRSxrQkFBa0IsRUFBRSxJQUFJLEVBQUUsQ0FBQyxnQkFBZ0IsQ0FBQyxFQUFDO0NBQ25GLENBQUMsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogQGxpY2Vuc2VcbiAqIENvcHlyaWdodCBHb29nbGUgSW5jLiBBbGwgUmlnaHRzIFJlc2VydmVkLlxuICpcbiAqIFVzZSBvZiB0aGlzIHNvdXJjZSBjb2RlIGlzIGdvdmVybmVkIGJ5IGFuIE1JVC1zdHlsZSBsaWNlbnNlIHRoYXQgY2FuIGJlXG4gKiBmb3VuZCBpbiB0aGUgTElDRU5TRSBmaWxlIGF0IGh0dHBzOi8vYW5ndWxhci5pby9saWNlbnNlXG4gKi9cblxuaW1wb3J0IHtDT01QSUxFUl9PUFRJT05TLCBDb21waWxlckZhY3RvcnksIFBsYXRmb3JtUmVmLCBTdGF0aWNQcm92aWRlciwgY3JlYXRlUGxhdGZvcm1GYWN0b3J5LCBwbGF0Zm9ybUNvcmV9IGZyb20gJ0Bhbmd1bGFyL2NvcmUnO1xuaW1wb3J0IHtKaXRDb21waWxlckZhY3Rvcnl9IGZyb20gJy4vY29tcGlsZXJfZmFjdG9yeSc7XG5cbi8qKlxuICogQSBwbGF0Zm9ybSB0aGF0IGluY2x1ZGVkIGNvcmVQbGF0Zm9ybSBhbmQgdGhlIGNvbXBpbGVyLlxuICpcbiAqIEBleHBlcmltZW50YWxcbiAqL1xuZXhwb3J0IGNvbnN0IHBsYXRmb3JtQ29yZUR5bmFtaWMgPSBjcmVhdGVQbGF0Zm9ybUZhY3RvcnkocGxhdGZvcm1Db3JlLCAnY29yZUR5bmFtaWMnLCBbXG4gIHtwcm92aWRlOiBDT01QSUxFUl9PUFRJT05TLCB1c2VWYWx1ZToge30sIG11bHRpOiB0cnVlfSxcbiAge3Byb3ZpZGU6IENvbXBpbGVyRmFjdG9yeSwgdXNlQ2xhc3M6IEppdENvbXBpbGVyRmFjdG9yeSwgZGVwczogW0NPTVBJTEVSX09QVElPTlNdfSxcbl0pO1xuIl19'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readJsonSync (/opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/node_modules/read-json-sync/index.js:10:31)
    at loadSourceMap (/opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/node_modules/liferay-npm-bundler/lib/util.js:93:36)
    at /opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/node_modules/liferay-npm-bundler/lib/runners.js:140:46
    at new Promise (<anonymous>)
    at /opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/node_modules/liferay-npm-bundler/lib/runners.js:127:11
    at Array.map (<anonymous>)
    at /opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/node_modules/liferay-npm-bundler/lib/runners.js:126:28
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/projects/arena-ui/master/arena-ui/apps/angular-npm-portlet/build/resources/main/META-INF/resources/node_modules/@angular%2Fplatform-browser-dynamic@6.0.4/esm2015/src/data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxhdGZvcm1fY29yZV9keW5hbWljLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vLi4vLi4vLi4vLi4vcGFja2FnZXMvcGxhdGZvcm0tYnJvd3Nlci1keW5hbWljL3NyYy9wbGF0Zm9ybV9jb3JlX2R5bmFtaWMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7QUFRQSxPQUFPLEVBQUMsZ0JBQWdCLEVBQUUsZUFBZSxFQUErQixxQkFBcUIsRUFBRSxZQUFZLEVBQUMsTUFBTSxlQUFlLENBQUM7QUFDbEksT0FBTyxFQUFDLGtCQUFrQixFQUFDLE1BQU0sb0JBQW9CLENBQUM7Ozs7OztBQU90RCxNQUFNLENBQUMsdUJBQU0sbUJBQW1CLEdBQUcscUJBQXFCLENBQUMsWUFBWSxFQUFFLGFBQWEsRUFBRTtJQUNwRixFQUFDLE9BQU8sRUFBRSxnQkFBZ0IsRUFBRSxRQUFRLEVBQUUsRUFBRSxFQUFFLEtBQUssRUFBRSxJQUFJLEVBQUM7SUFDdEQsRUFBQyxPQUFPLEVBQUUsZUFBZSxFQUFFLFFBQVEsRUFBRSxrQkFBa0IsRUFBRSxJQUFJLEVBQUUsQ0FBQyxnQkFBZ0IsQ0FBQyxFQUFDO0NBQ25GLENBQUMsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogQGxpY2Vuc2VcbiAqIENvcHlyaWdodCBHb29nbGUgSW5jLiBBbGwgUmlnaHRzIFJlc2VydmVkLlxuICpcbiAqIFVzZSBvZiB0aGlzIHNvdXJjZSBjb2RlIGlzIGdvdmVybmVkIGJ5IGFuIE1JVC1zdHlsZSBsaWNlbnNlIHRoYXQgY2FuIGJlXG4gKiBmb3VuZCBpbiB0aGUgTElDRU5TRSBmaWxlIGF0IGh0dHBzOi8vYW5ndWxhci5pby9saWNlbnNlXG4gKi9cblxuaW1wb3J0IHtDT01QSUxFUl9PUFRJT05TLCBDb21waWxlckZhY3RvcnksIFBsYXRmb3JtUmVmLCBTdGF0aWNQcm92aWRlciwgY3JlYXRlUGxhdGZvcm1GYWN0b3J5LCBwbGF0Zm9ybUNvcmV9IGZyb20gJ0Bhbmd1bGFyL2NvcmUnO1xuaW1wb3J0IHtKaXRDb21waWxlckZhY3Rvcnl9IGZyb20gJy4vY29tcGlsZXJfZmFjdG9yeSc7XG5cbi8qKlxuICogQSBwbGF0Zm9ybSB0aGF0IGluY2x1ZGVkIGNvcmVQbGF0Zm9ybSBhbmQgdGhlIGNvbXBpbGVyLlxuICpcbiAqIEBleHBlcmltZW50YWxcbiAqL1xuZXhwb3J0IGNvbnN0IHBsYXRmb3JtQ29yZUR5bmFtaWMgPSBjcmVhdGVQbGF0Zm9ybUZhY3RvcnkocGxhdGZvcm1Db3JlLCAnY29yZUR5bmFtaWMnLCBbXG4gIHtwcm92aWRlOiBDT01QSUxFUl9PUFRJT05TLCB1c2VWYWx1ZToge30sIG11bHRpOiB0cnVlfSxcbiAge3Byb3ZpZGU6IENvbXBpbGVyRmFjdG9yeSwgdXNlQ2xhc3M6IEppdENvbXBpbGVyRmFjdG9yeSwgZGVwczogW0NPTVBJTEVSX09QVElPTlNdfSxcbl0pO1xuIl19' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-npm-portlet@1.0.0 build: `tsc && liferay-npm-bundler`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-npm-portlet@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wos/.npm/_logs/2018-06-13T20_40_03_318Z-debug.log
</pre>

**Comment by vswom** [comment]
up

**Comment by izaera** [comment]
Looks like it is a problem with inlined source maps:

<img width="882" alt="imagen" src="https://user-images.githubusercontent.com/3273630/41595820-743c7c5c-73c8-11e8-850d-d49afa0e735f.png">

**Comment by izaera** [comment]
There's also a problem with `rxjs@6.2.1` package because its `operators/index.js` is incorrectly named as `rxjs621$rxjs/operators@undefined/index`.

That is because the `rxjs/operators` has a `package.json` file without `version` field (because it is just a directory inside a package) and the [babel-plugin-name-amd-modules](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-name-amd-modules) mistakingly thinks that the package's version is `undefined`.

**Comment by izaera** [comment]
Given that there's more than one issue, I'll create specific issues per bug and start resolving them until everything works.

I'll use this issue as an umbrella to gather them all.

**Comment by wsyski** [comment]
Thanks again. Sorry to bother you with my question, but let me describe what are my challenges. The company I am working for is using Liferay 7.0.6 GA7. There is no way I could convince them to use Liferay 7.1 since this is not a stable version yet. The only way for me is to make changes in the existing 7.0.6 code base. I know that you can not guarantee anything, but just up to your best knowledge what should I port from 7.1 Liferay branch to 7.0 branch to get the latest npm bundler working. Do you think that I should try to upgrade the amd loader to 3.1.1? Would everything else work if I do it? Is it worth trying with the existing 2.3.0, or there is something that you know it will not work. I do not expect any guarantee from you, but just the best guess.

**Comment by izaera** [comment]
AFAIK the only bug waiting to arrive at 7.0 is [LPS-82429](https://issues.liferay.com/browse/LPS-82429) but it may not hit you. Regarding the loader you shouldn't need to upgrade. At least the last time I tested 7.0 everything worked as expected in the loader.

**Comment by wsyski** [comment]
I have tested your example:
git@github.com:izaera/liferay-npm-bundler-2-example.git
It works fine in the Liferay 7.1.x branch, but not in Liferay 7 GA. I suspect that the new amd loader 3.1.1 is a major factor there. Is it safe to replace amd loader 2.3.0 in Liferay 7 GA? Is it backward compatible?

**Comment by wsyski** [comment]
Just FYI. I got angular 6 working in custom 7.0.6 GA7 working.
I have just back-ported from 7.1.x: 
1. com.liferay.frontend.js.bundle.config.extender.api
2. com.liferay.frontend.js.bundle.config.extender
3. com.liferay.frontend.js.node.shims
4. com.liferay.frontend.js.minifier
Afterwards upgraded:
1. Liferay npm bundler and loader to the latest version.
Now I can run all 7.1.x angular examples.

**Comment by izaera** [comment]
Good job 👏
