### ISSUE TITLE
Question about bundling and JS aggregation

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-npm-build-tools#153]
So does this architecture and tool set result in any sort of JS aggregation ala Webpack/Browserify?

Or if a portlet has a dependency tree of npm modules that say results in total of 30 or 40 packages (modules) being needed/used by that portlet, do each of those modules result in a unique http request being generated from the browser when it detects each dependency?

My sense of reading the doco is that the answer to that question is 'no' (no aggregation)  in order to build/preserve a unique set/registry of "modules in use" across the entire portal page?

Thanks

**Comment by izaera** [comment]
Your sense is correct ;-).

We don't do any aggregation because otherwise we would be mimicking webpack and in that case it would be much better to use webpack directly.

We publish each npm module (not package) as a single entity and that would, intuitively, result in one request per module but, Liferay comes with combo servlet active by default, which aggregates several loader requests into one (limited by a combined URL size of around 2048 chars). In case the aggregation exceeds the 2048 limit new aggregation requests are issued until all modules are retrieved from the server.

So, we don't do aggregation on build time (like webpack does) but in runtime. This is necessary because, given that we may have several portlets in one page and we don't know them in advance, we cannot optimize the bundling until the page is composed and all shared modules are resolved.

So, say you have 5 portlets that use Angular in the same page. With webpack you would have 5 copies of Angular in memory, while with our bundler (in version 2.x) you could configure an Angular provider handler and make the 5 portlets use the same copy.

**Comment by mfreeman-xtivia** [comment]
So to complete my understanding to this question, I'd love to know more if you have some pointers to two topics you mentioned:

1--Any more info on how the combo servlet works to do run-time aggregation?
2--What's a "provider handler"? I assume that's something new in version 2.x of these npm tools, but I don't remember seeing it anywhere

**Comment by izaera** [comment]
1. I'm not sure if we have documentation about it. It's implemented in [this class](https://github.com/liferay/liferay-portal/blob/d9883da1a7df9de7b72d9aa8984e20693ab8112d/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java). It basically receives a bunch of URLs as the request's query string, splits them, forwards them to their handlers, and combines the responses into one single output. You can open the browser's dev tools, hit a portal's web page and look for any requests to the `combo` endpoint to see it in action. It's enabled by default.

2. I meant Angular Provider _bundle_, not _handler_ :-S (I have updated my previous commit accordingly).

**Comment by izaera** [comment]
In the [example angular app](https://github.com/izaera/liferay-npm-bundler-2-example) described in the third blog post about the bundler, [this](https://github.com/izaera/liferay-npm-bundler-2-example/tree/master/modules/npm-angular5-provider) is the provider, and [this](https://github.com/izaera/liferay-npm-bundler-2-example/tree/master/modules/npm-angular5-portlet-say-hello) is the consumer.

**Comment by mfreeman-xtivia** [comment]
And the JS loader on the client side uses this combo loader servlet endpoint intuitively? always? in cetain cases?

**Comment by mfreeman-xtivia** [comment]
Sorry for the insane number of questions here---but that naturally leads to a follow up question of how does the JS loader know when/how to group requests to the combo loader servlet? is there some external notion of "oh when we are processing the load request for X (a portlet?) we will wait until we have the entire list of dependencies before we invoke the combo loader?

**Comment by izaera** [comment]
The loader groups all the modules belonging to a `require()` call. For example, say you do:

```javascript
require('my-module', function(myModule) {
  myModule.run();
});
```

When you issue the `require` the loader recursively traverses the dependency tree of `my-module` and stores all of them in a sorted list (deeper dependencies first). It then combines the URLs to those dependencies in a combo call. As I said, if after ~2048 chars or URL not all modules have been listed, it created another request and so on.

On the contrary, if the combo servlet is disabled, it launches one request per module and instantiates them in the correct order: leaf dependencies first, then the previous level, ..., until it instantiates `my-module`.

**Comment by mfreeman-xtivia** [comment]
Are all of these features available to play with in the Liferay 7.0 world or do I need to download and use the 7.1 beta to play with them?

**Comment by izaera** [comment]
The plan is to maintain the same in 7.0 and 7.1 so you can go ahead an use 7.0 GA7 (the only thing missing for that version is [LPS-82429](https://issues.liferay.com/browse/LPS-82429), I think).

**Comment by mfreeman-xtivia** [comment]
And somewhere in this process, presumably in the npm-bundler, npm modules that are actually composed of multiple JS files in "real life", are somehow converted to a single file, AMD-based version of themselves for subsequent consumption by the Liferay JS loader/combo servlet etc

**Comment by izaera** [comment]
All that is true except that there can't be `modules composed of multiple JS files`. One file => one module as in Node.js.

So you have `packages` like [react](https://www.npmjs.com/package/react) that contain `modules` like [React](https://github.com/facebook/react/blob/master/packages/react/src/React.js), [ReactBaseClasses](https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js), ...

**Comment by mfreeman-xtivia** [comment]
Right you are. I need to be more precise. 

So when does the "AMD-ification" of *modules* take place? And does it really always convert them from CJS to AMD, or leave theme alone if they are already using UMD, etc?

**Comment by izaera** [comment]
The "AMD-ification" takes place when liferay-npm-bundler invokes the [babel-plugin-wrap-modules-amd](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-wrap-modules-amd) plugin passing it each JS module file. That wraps everything in a `define()` call. 

Then [babel-plugin-name-amd-modules](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-name-amd-modules) gives a name to the modules.

And then [babel-plugin-namespace-amd-define](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-namespace-amd-define) prepends `Liferay.Loader.` to the define call.

To finish with, [babel-plugin-namespace-modules](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-namespace-modules) namespaces module names prefixing them with the package name plus the `$` separator.

All this is explained in their README files.

Regarding UMD, the [babel-plugin-wrap-modules-amd](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-wrap-modules-amd) [emits some code](https://github.com/liferay/liferay-npm-build-tools/blob/master/packages/babel-plugin-wrap-modules-amd/src/index.js#L8) (`var define = undefined;`) before the module itself to make UMD modules think that they are inside a CommonJS architecture and prevent them from colliding with the wrapping `define()` we add.
