### ISSUE TITLE
How do I switch from bundler 1.x to 2.x?

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#161]
1. First of all, read the [three blog posts](https://community.liferay.com/blogs/-/blogs/why-we-need-a-new-liferay-npm-bundler-1-of-3-) explaining the changes made in 2.x version series.

2. Then, head on to your bundler based project, update `liferay-npm-bundler` dependency to `^2.0.0` and remove any `liferay-npm-bundler-preset-...` dependency (as bundler 2.x already comes with those inside).

3. Edit your `.npmbundlerrc` file and remove any preset you had configured.

4. Do one of:

* **If you used Babel to transpile your project's code:**

Remove any `babel-preset-...` or `babel-plugin-...` dependencies contained in this repository and/or not directly used by your project.

For example, nearly all bundler 1.x projects used [babel-preset-liferay-project](https://github.com/liferay/liferay-npm-build-tools/tree/1.x/packages/babel-preset-liferay-project) in addition to anything else you were using to transpile your code.

Then edit your `.babelrc` and remove all the previous removed presets/plugins from the configuration.

* **If you don't need Babel to transpile your project's code:**

In this case just remove any Babel related dependency directly and delete any `.babelrc` file hanging around.

**Comment by jbalsas** [comment]
Hey @izaera, could we move this info into the Wiki for future reference? 🙏

**Comment by izaera** [comment]
@jbalsas It's indirectly in the wiki in https://github.com/liferay/liferay-npm-build-tools/wiki , section 3/iv

But if you want to emphasize it maybe we could add a section with highlighted links... 🤔

**Comment by jbalsas** [comment]
🤔 ...

Maybe we could add a manual entry... Migrating from bundler 1.x to bundler 2.x, and then just pretty much dump this content there?
