### ISSUE TITLE
When running npm run start on windows syntax error

### ISSUE THREAD

**Issue by micduffy** [liferay/liferay-npm-build-tools#217]
I have used the generator-liferay-bundle to generate a react porlet - and when I run 
npm run start

I recieve the following error : 
C:\projects\my-project>npm run start

> my-project@1.0.0 start C:\projects\my-project
> lnbs-start

C:\projects\my-project\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by micduffy** [comment]
Thanks Ivan - I can confirm it works under unix, and under osx - I can assist with my analysis on the windows portion. Please let me know if you need any questions answered.

**Comment by izaera** [comment]
The problem is clear: I'm executing the `webpack-dev-server` script directly and that launches the unix version on Windows :-(.

**Comment by micduffy** [comment]
Thats what it seemed like this side. Thanks for picking this one up. Thanks Ivan.

**Comment by izaera** [comment]
I will add an npm script in package.json to launch `webpack-dev-server` so that it is platform agnostic. Thx for the report :-).

**Comment by izaera** [comment]
Nope. If I do that I will break already generated projects. So, to maintain compatibility, I will test for Windows and run the `.cmd` file instead.

**Comment by micduffy** [comment]
saw this in runWebpackDevServer in .\node_modules\liferay-npm-build-support\lib\scripts\start.js - i tried to retrofit win-spawn in place of spawn but got lost... when i hard coded 
var webpackDevServerPath = _path2.default.resolve(_path2.default.join(cfg.getProjectDir(), 'node_modules', '.bin', 'webpack-dev-server.cmd')); 
it still broke... 

hope this helps

**Comment by izaera** [comment]
Fixed :-). I'll make a release soon (probably today or tomorrow).

**Comment by micduffy** [comment]
Legend ! Thanks Ivan

**Comment by izaera** [comment]
@micduffy `2.5.0` is out and should fix this error. You can either update your project's packages or run the generator again (after updating it, of course).
