### ISSUE TITLE
Running npm run start on windows causes compilation failure for JSX source

### ISSUE THREAD

**Issue by micduffy** [liferay/liferay-npm-build-tools#219]
When I use the generator-liferay-bundle on Windows, the following output happens when I run 
npm run start

Entrypoint main = webpack.bundle.js webpack.bundle.js.map
[../node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[../node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[../node_modules/events/events.js] 8.13 KiB {main} [built]
[../node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[../node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[0] multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ./index.js 40 bytes {main} [built]
[../node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[../node_modules/url/url.js] 22.8 KiB {main} [built]
[../node_modules/webpack-dev-server/client/index.js?http://localhost:8080] ../node_modules/webpack-dev-server/client?http://loca
lhost:8080 7.78 KiB {main} [built]

[../node_modules/webpack-dev-server/client/overlay.js] 3.58 KiB {main} [built]
[../node_modules/webpack-dev-server/client/socket.js] 1.05 KiB {main} [built]
[../node_modules/webpack/hot sync ^\.\/log$] ../node_modules/webpack/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[../node_modules/webpack/hot/emitter.js] 77 bytes {main} [built]
[../src/index.js] 277 bytes {main} [built] [failed] [1 error]
[./index.js] 206 bytes {main} [built]
    + 12 hidden modules

**ERROR in ../src/index.js 32:8**
Module parse failed: Unexpected token (32:8)
You may need an appropriate loader to handle this file type.
|
|     ReactDOM.render(
>         <AppComponent
|             portletNamespace={portletNamespace}
|             contextPath={contextPath}
 @ ./index.js 1:11-37
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ./index.js

I would attribute this to the following lines in 
liferay-npm-build-support\lib\scripts\start.js in function runWebpackDevServer() where in windows, the logic is to run (on line 125)
proc = _child_process2.default.spawn(webpackDevServerPath, [], { (webpack with no arguments)

**Comment by izaera** [comment]
@micduffy why do you think those lines are the culprit? I can't see any difference between windows and unix' executions of `webpack-dev-server` (appart from the .cmd extension, of course) 🤔

**Comment by izaera** [comment]
Got it! The problem is with the `.npmbuildrc` file. Instead of:

```json
{
        "webpack": {
                "rules": [
                        {
                                "test": "src\\/.*\\.js$",
                                "use": "babel-loader"
                        }
                ]
        }
}
```

it should say:

```json
{
        "webpack": {
                "rules": [
                        {
                                "test": "src\\\\.*\\.js$",
                                "use": "babel-loader"
                        }
                ]
        }
}
```

for Windows. Note the change in the `test` property

**Comment by micduffy** [comment]
> Got it! The problem is with the `.npmbuildrc` file. Instead of:
> 
> ```json
> {
>         "webpack": {
>                 "rules": [
>                         {
>                                 "test": "src\\/.*\\.js$",
>                                 "use": "babel-loader"
>                         }
>                 ]
>         }
> }
> ```
> 
> it should say:
> 
> ```json
> {
>         "webpack": {
>                 "rules": [
>                         {
>                                 "test": "src\\\\.*\\.js$",
>                                 "use": "babel-loader"
>                         }
>                 ]
>         }
> }
> ```
> 
> for Windows. Note the change in the `test` property

The one for angular bundles is 
{
	"webpack": {
		"rules": [
			{
				"test": "src\\\\.*\\.ts$",
				"use": "ts-loader"
			}
		],
		"extensions": [
			".ts",
			".js"
		],
		"mainModule": "index.ts"
	}
}
