### ISSUE TITLE
Best practice for using "liferayDir" within a Liferay Workspace

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-npm-build-tools#238]
Currently the value for `liferayDir` is set to the user that uses the generator. Do you think we could update this to also accept flag value like `--liferayDir`. This way if a user is using gradle to build their modules they can possibly just pass 
```
node.npmArgs = "--liferayDir ${project.hasProperty('liferay.workspace.home.dir') ? project.property('liferay.workspace.home.dir') : 'bundles'}"
```

from build.gradle to set the value to `liferayDir`.

**Comment by izaera** [comment]
You can also use relative paths in `.npmbuildrc` in case it helps. If the project is inside a blade workspace you can just point to the root `bundles` folder and it should work.
