### ISSUE TITLE
Fixing "Package MODULE_NAME$zlib which is a dependency of MODULE_NAME$pdfjs-dist@2.0.943 is not deployed in the server" error

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-npm-build-tools#267]
Hey guys,

I am posting this here more as a question. A client is working with https://github.com/mozilla/pdfjs-dist which includes requires that are native to node.js such has `zlib`. Within their code they contain throwing warnings when they are not available. It appears that when the bundler is running it comes across that line in the AST and just adds it like `MODULE_NAME$zlib` to the file which will then throw an error on the page. 

Am I missing anything for configuring the npm bundler to work with packages like this? Thanks!

**Comment by izaera** [comment]
If you are going to use node packages, you need to import them from the `frontend-js-node-shims` bundle (shipped with the portal) or provide them with your own bundle.

The "problem" is that the bundler doesn't know that `zlib` is an special module. It just sees that it is not in your `package.json` and treats it like a local path. You could argue that we could check the paths to see if the module really exists, but that would add more time to the build which already is time consuming, and provide little value. 

So if it is really really needed in your case, you can use the shims or configure a babel plugin in the bundler to remove that calls, for example. That should fix it.

Alternatively, if we see that this pattern is very usual, we may provide some functionality (a preset for example) in the bundler to bypass it. But it would do more or less the same I'm telling you in the previous paragraph...
