### ISSUE TITLE
liferay-npm-bundler fails if no .npmbundlerrc file is found

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#29]
A way to fix this would be running `liferay-npm-bundler-preset-standard` by default if no `.npmbundlerrc` file is found.

**Comment by jbalsas** [comment]
Do you mean running `liferay-npm-bundler-preset-standard`?

**Comment by izaera** [comment]
Yes. I copy pasted the wrong name.

**Comment by izaera** [comment]
Oops, I have fixed this with #39, but it assumes an empty .npmbundlerrc instead of sensible defaults, like `liferay-npm-bundler-preset-standard`.

Shall we change the behavior of #39 in favor of using `liferay-npm-bundler-preset-standard` or leave it like that? 

What do you think @jbalsas?

**Comment by jbalsas** [comment]
Let's live it like is for now and see what people expect from using it without a config.

**Comment by izaera** [comment]
After looking at it in more detail, we will finally set `liferay-npm-bundler-preset-standard` as the default preset because it follows the more usual build lifecycle.

**Comment by izaera** [comment]
Oops! This is far more difficult than I thought. Babel doesn't do it either.

The technical problem is that if the bundler assumes a default preset, it has to include the preset internally because the project (to which the bundler is being applied) won't have it. That could be done, but it wouldn't leave control to the user about the version of the preset to use.

Then, we could let users override the preset version by adding a .npmbundlerrc file, but it would make the plugins resolution more complex and could lead to inconsistencies, so I find it safer not to assume a default preset.
