### ISSUE TITLE
features/configuration.json with yo liferay-bundle react doesn't work

### ISSUE THREAD

**Issue by iopazo** [liferay/liferay-npm-build-tools#314]
Hi!
I'm try to create configuration for a portlet created with yo liferay-bundle.
The problem i have when i create the folder features and configure it on .npmbundlerrc, the configuration on portlet settings and system settings doen't show on liferay portal.

This is my .npmbundlerrc

```
{
	"create-jar": {
		"output-dir": "dist",
		"features": {
			"js-extender": true,
			"web-context": "/portlet-banner",
			"configuration": "features/configuration.json"
		}
	},
	"dump-report": true
}
```

and this is my project tree folder:

![Screen Shot 2019-04-16 at 5 58 59 PM](https://user-images.githubusercontent.com/432525/56247077-a954f900-6071-11e9-8286-5f127b29cef7.png)

And my package.json:

```
{
	"name": "portlet-banner",
	"version": "1.0.0",
	"description": "Portlet Banner",
	"devDependencies": {
		"babel-cli": "^6.26.0",
		"babel-loader": "^7.0.0",
		"babel-preset-env": "^1.7.0",
		"babel-preset-react": "^6.0.0",
		"copy-webpack-plugin": "^4.5.4",
		**"liferay-npm-build-support": "^2.6.2",
		"liferay-npm-bundler": "^2.6.2",**
		"webpack": "^4.0.0",
		"webpack-cli": "^3.0.0",
		"webpack-dev-server": "^3.0.0"
	},
	"dependencies": {
		"react": "^16.0.0",
		"react-dom": "^16.0.0"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
	"portlet": {
		"com.liferay.portlet.display-category": "category.uno",
		"com.liferay.portlet.header-portlet-css": "/css/styles.css",
		"com.liferay.portlet.instanceable": true,
		"javax.portlet.name": "portlet_banner",
		"javax.portlet.security-role-ref": "power-user,user",
		"javax.portlet.display-name": "Portlet Banner"
	},
	"main": "index.js"
}
```

As you can see, liferay-npm-bundler and build-support are in 2.6.2 version, when i change to 2.7.0 like you say in this link https://github.com/liferay/liferay-npm-build-tools/issues/262.

When i change the version and run deploy on terminal, catalina.sh show me this error:
`ERROR [fileinstall-/Users/iopazo/Develop/Liferay/Master/osgi/modules][org_apache_felix_fileinstall:97] Error while starting bundle: file:/Users/iopazo/Develop/Liferay/Master/osgi/modules/portlet-banner-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: portlet-banner [1010]_  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=liferay.frontend.js.portlet)(version>=1.1.0))"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1258)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1230)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1218)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:507)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)
`
If you can give me a hand with this and try to understand what im doing wrong plz.

Thanks!

**Comment by wincent** [comment]
@iopazo: If you look at the "versions" tab of `generator-liferay-bundle` you'll see that v2.6.2 is currently marked as "latest", which is why you get it if you `npm install generator-liferay-bundle`. If you want to try v2.7.1, then I suggest installing it with `npm install generator-liferay-bundle@canary`, and that way you won't have to manually manipulate "package.json" versions.

I'm not actually sure about the error message you're seeing though. @izaera is out this week but may be able to point you in the right direction when he gets back.

**Comment by iopazo** [comment]
Hi @wincent, thanks for answer.

I have no doubts about the version of generator-liferay-bundle. Actually the version 2.6.2 its the only one that works well.

My questions its about how make a portlet have a configuration settings on Liferay Portal, for example:

![Screen Shot 2019-04-17 at 9 11 46 AM](https://user-images.githubusercontent.com/432525/56290359-f5934e00-60f0-11e9-88d1-73179a8d6146.png)

I follow this guide https://github.com/liferay/liferay-npm-build-tools/wiki/.npmbundlerrc-file-reference#create-jarfeaturesconfiguration, but i can't make works on Portal Liferay 7.1 CE.

I need to create a Setup Tab for every portlet i created with yeoman (liferay-bundle) on react. This its my portlet:
![Screen Shot 2019-04-17 at 9 19 25 AM](https://user-images.githubusercontent.com/432525/56290814-fa0c3680-60f1-11e9-89be-227fc13c67bf.png)

If you can give me more details about this I'll be very greatful.

Thanks!

**Comment by izaera** [comment]
I think the problem is that you need [JS Portlet Extender](https://web.liferay.com/marketplace/-/mp/application/115543020) 1.1.0 (see https://github.com/liferay/liferay-npm-build-tools/wiki/Configuring-pure-javascript-projects#configuration) which is not yet released :-( .

**Comment by iopazo** [comment]
Thank you @izaera, when you think this version will be already to release?

**Comment by izaera** [comment]
@iopazo Not sure. I'll start working on the release today, but some steps in the process don't depend on me. I guess it will be 1-2 weeks if everything goes well.
