### ISSUE TITLE
Module names are incorrectly generated in Windows

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#47]
The bundler is mixing / and \ path separators and incorrectly generates module names in Windows.

**Comment by blzaugg** [comment]
I'm going to be testing the bundler for LDN. Is this going to prevent/block me from completing?

I'm on Windows 7.

**Comment by izaera** [comment]
@blzaugg Yes it will block you :-(. But I'm fixing it today, so maybe when you get to the office it is working.
