### ISSUE TITLE
The inject-angular-dependencies plugin fails for @angular/animations

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#66]
Currently, if the user includes `@angular/animations` as a dependency of his project, the `peerDependencies` in `@angular/platform-browser` are not being transformed to `dependencies` and that makes the portlet fail because it cannot load the proper `@angular/animations`.

**Comment by yuchi** [comment]
Isn't this a more common scenario that is not limited to angular? And also, does solving peer deps altogether solve also this issue?

**Comment by izaera** [comment]
@yuchi Yes and yes ;-)

**Comment by izaera** [comment]
We will do it in the near future.

**Comment by ntrp** [comment]
Tried to deploy the npm-angular-portlet sample (after updating all tooling to 1.4.0) on a Liferay DXP fixpack 37 server and the application doesn't run. I get this error:
![2018-01-25-160155_1557x359_scrot](https://user-images.githubusercontent.com/720492/35394873-2a079262-01e9-11e8-8dcb-6088cff7ea63.png)
Note that there is no inclusion of angular animations or other sub-module..

**Comment by izaera** [comment]
@ntrp @beall49 I'm investigating it right now. Will keep you updated in this thread.

**Comment by ntrp** [comment]
Just as additional info, on patch 37 neither the webpack angular portlet works anymore for me. I get a "define is not defined" error when trying to initialize a webpack AMD named module with the config.js file.

**Comment by izaera** [comment]
This is the exact problem -> https://github.com/liferay/liferay-npm-build-tools/issues/74

**Comment by ntrp** [comment]
But I am not using the npm build tools for the angular portlet. I am creating a webpack bundle and just configuring a liferay module with:
```Javascript
Liferay.Loader.addModule(
  {
    dependencies: [],
    name: 'app',
    path: MODULE_PATH + '/js/app.js'
  }
);
```
On patch 34 it works but not on patch 37

**Comment by izaera** [comment]
Don't know what can be happening with webpack, but in any case it should be filed as a different bug (a portal bug) if it needs to be resolved. However I'm planning a release of these build tools to make the angular portlet work.

**Comment by izaera** [comment]
So, I have released version 1.4.1 of liferay-npm-build-tools. 

@ntrp Can you please update your portlet's package.json and see if it works with FP37? Thx :-)

**Comment by ntrp** [comment]
[angular-npm-portlet.zip](https://github.com/liferay/liferay-npm-build-tools/files/1678162/angular-npm-portlet.zip)

Just tried with fix pack 37 and the attached project source, the result is the following:

![2018-01-30-160020_3822x285_scrot](https://user-images.githubusercontent.com/720492/35573230-c6866398-05d6-11e8-9a45-bec08f71d0ed.png)

**Comment by izaera** [comment]
@ntrp I have just deployed your portlet and it works. I even get the routing thing to work:

<img width="275" alt="imagen" src="https://user-images.githubusercontent.com/3273630/35574799-158dbe2e-05db-11e8-98f8-7de11f5ac011.png">

Have you tried to remove node_modules, `npm install` and then `gradle clean deploy`?

**Comment by ntrp** [comment]
I tested a little and I can confirm it works with angular 4.2.3 but unfortunately it doesn't with the version 4.3.0 on.. We where planning on using Angualr 5.2.2 (latest) for the project also because we are generating the API service layer with ng-swagger-gen.

![2018-01-30-170951_3823x359_scrot](https://user-images.githubusercontent.com/720492/35576962-adc03ffa-05e0-11e8-9919-f45373459c75.png)

Would it be possible to make it work with Angular 5.2.2 somehow?

**Comment by izaera** [comment]
Mmm, there's a known issue with Angular 5 I believe (see here: https://web.liferay.com/community/forums/-/message_boards/view_message/102908519) but I have plans to fix it too.

Regarding 4.3.0 I don't know what could be the problem. In theory, rxjs version constraints should be correctly injected by the [liferay-npm-bundler-plugin-inject-angular-dependencies](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/liferay-npm-bundler-plugin-inject-angular-dependencies).

Let me check.

**Comment by izaera** [comment]
4.3.0 works. Remember to clean your node_modules and do gradle clean build.

**Comment by izaera** [comment]
@ntrp ☝️

**Comment by ntrp** [comment]
I forgot to mention that we need also rxjs 5.5.x because of the swagger interface generation. Anyway I guess we will use webpack until it's stable, in the meantime we are following up the problem in LESA.
