### ISSUE TITLE
Avoid collisions between options and package configurations in .npmbundlerrc file

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#69]
Right now, options like `exclude` or `output` are directly written at the root level of `.npmbundlerrc` file. This may cause collisions with package names (in fact there is one npm package called `exclude` 😬).

These options should be moved to their own section to avoid collisions.

**Comment by izaera** [comment]
We will call the new section `.options`

**Comment by izaera** [comment]
It may be better to just move packages to a `packages` section and leave the options in the root. That way, retro compatibility would be easier and we wouldn't have to change so many docs. In addition in looks better.

**Comment by jbalsas** [comment]
Sounds good to me! 👍

**Comment by yuchi** [comment]
> It may be better to just move `packages` to a packages section…

I was going to suggest just that, so waaay better IMHO.

No time to check the diffs, did you implement a compatibility mode if no `packages` prop is set?

**Comment by izaera** [comment]
> No time to check the diffs, did you implement a compatibility mode if no packages prop is set?

Yes.

**Comment by yuchi** [comment]
Cool
