### ISSUE TITLE
Include transform-object-assign plugin to the default liferay presets

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-build-tools#76]
Since we support IE11, we should include by default https://babeljs.io/docs/plugins/transform-object-assign/ so we don't get tripped by `Object.assign` usage.

**Comment by izaera** [comment]
After discussing it, we won't implement this for two reasons:

1) If the code using `Object.assign` is not in a third party library, there's nothing the bundler can do as it doesn't process project's source code.
2) If the code using `Object.assign` is in a third party library then it's the responsibility of that library to work for IE11. If the developer hasn't paid attention to not using `Object.assign` chances are that the code will fail in IE11 for more reasons. 

Also, even if the bundler patched the `Object.assign` it is still much more elegant to polyfill it than transforming the code with Babel (IMO).
