### ISSUE TITLE
Portlet with Angular 2 (or more) at Liferay

### ISSUE THREAD

**Issue by mir592** [liferay/liferay-npm-build-tools#78]
Hi!
I'm trying to create a portlet with angular, with the example of the page of Liferay:  ([https://dev.liferay.com/es/develop/reference/-/knowledge_base/7-0/npm-angular-portlet-template](https://dev.liferay.com/es/develop/reference/-/knowledge_base/7-0/npm-angular-portlet-template))

The last problem I'm fighting with is that Eclipse doesn't find an file and this is the error that I can see at the console: _ERROR [http-nio-8080-exec-3][status_jsp:907] El recurso requerido /angular-npm-portlet@1.0.0.js no se encuentra disponible_ 
Could you know what could be happening? 
Thank you! :)

**Comment by izaera** [comment]
Hi there:

Unfortunately it is impossible to know what can be the problem with such little information :-(.

If it is still failing please open a new issue with more information on how to fix the problem and/or attach a zip file with steps to reproduce so we can have a look at it.

Thanks :-)
