### ISSUE TITLE
When using a local package in package.json an exception is thrown when bundling the project

### ISSUE THREAD

**Issue by julien** [liferay/liferay-npm-build-tools#79]
When using a local package in a `package.json` file, for example:

```json
{
  "dependencies": {
    "my-module": "/Users/me/my-module"
  }
}
```

An exception is thrown when trying to get the resolve the modules dependencies.

**Comment by izaera** [comment]
We need to account for `file:...`, `http:...`, `git:...`, etc. dependencies too. See https://docs.npmjs.com/files/package.json#dependencies for more info.
