### ISSUE TITLE
How can I opt out/in of sending analytic metrics after having given/denied consentment?

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-build-tools#92]
- For Mac users: just go to `~/Library/Preferences/insight-nodejs`, look for the `insight-<project>.json` file where `<project>` is the name of your project, and edit it, changing `optOut` to true or false as desired. If there's no `optOut` value, just add it.

**Comment by yuchi** [comment]
I was making an issue for this XD

**Comment by izaera** [comment]
Too late 😎 . It's difficult to be faster than you, but I'm making a lot of progress 😂
